name: CI
on:
  push:
    branches:
      - '**'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
          send-statistics: false
      - run: nix develop --command pnpm install --frozen-lockfile
      - run: nix develop --command pnpm run check
      - run: nix develop --command pnpm run lint
      - run: nix develop --command pnpm run test:unit
      - run: nix develop --command pnpm run test:integration
